### ISSUE TITLE
Bot slow down?

### ISSUE THREAD

**Issue by Cameron11598** [countervandalism/infrastructure#23] opened 2018-12-06 05:03 UTC
Bots were lagging out today; @Az1568 restarted possibly related to #22

**Comment by Cameron11598** [comment] 2018-12-06 05:03
4:36:29 PM <@AlexZ_> CVNBot1 restart
4:36:29 PM ← +CVNBot1 left (~CVNBot1@cvn/bot/cvn-bots): "Rebooting by order of AlexZ_ ..."
4:36:35 PM <@AlexZ_> CVNBot2 restart
4:36:36 PM ← +CVNBot2 left (~CVNBot2@cvn/bot/cvn-bots): "Rebooting by order of AlexZ_ ..."
4:36:38 PM <@AlexZ_> CVNBot3 restart
4:36:39 PM ← +CVNBot3 left (~CVNBot3@cvn/bot/cvn-bots): "Rebooting by order of AlexZ_ ..."
4:36:42 PM <@AlexZ_> CVNBot4 restart
4:36:42 PM ← +CVNBot4 left (~CVNBot4@cvn/bot/cvn-bots): "Rebooting by order of AlexZ_ ..."
4:36:44 PM → +CVNBot1 (voiced) joined  
4:36:46 PM <@AlexZ_> CVNBot5 restart
4:36:47 PM ← +CVNBot5 left (~CVNBot5@cvn/bot/cvn-bots2): "Rebooting by order of AlexZ_ ..."
4:36:51 PM <@AlexZ_> CVNBot6 restart
4:36:51 PM → +CVNBot2 (voiced) and +CVNBot3 (voiced) joined  ← +CVNBot6 left  
4:36:56 PM <@AlexZ_> CVNBot7 restart
4:36:56 PM → +CVNBot4 (voiced) joined  ← +CVNBot7 left  
4:37:03 PM <@AlexZ_> CVNBot8 restart
4:37:04 PM → +CVNBot5 (voiced) joined  ← +CVNBot8 left  
4:37:08 PM <@AlexZ_> CVNBot9 restart
4:37:09 PM → +CVNBot6 (voiced) joined  ← +CVNBot9 left  
4:37:13 PM <@AlexZ_> CVNBot10 restart
4:37:14 PM → +CVNBot7 (voiced) joined  ← +CVNBot10 left  
4:37:19 PM <@AlexZ_> CVNBot12 restart
4:37:19 PM → +CVNBot8 (voiced) joined  ← +CVNBot12 left  
4:37:24 PM <@AlexZ_> CVNBot13 restart
4:37:24 PM → +CVNBot9 (voiced) joined  ← +CVNBot13 left  
4:37:28 PM <@AlexZ_> CVNBot14 restart
4:37:29 PM → +CVNBot10 (voiced) joined  ← +CVNBot14 left  
4:37:31 PM <@AlexZ_> CVNBot15 restart
4:37:34 PM → +CVNBot12 (voiced) joined  
4:37:35 PM <@AlexZ_> CVNBot16 restart
4:37:35 PM ← +CVNBot16 left (~CVNBot16@cvn/bot/cvn-bots3): "Rebooting by order of AlexZ_ ..."
4:37:40 PM <@AlexZ_> CVNBot17 restart
4:37:40 PM → +CVNBot13 (voiced) joined  ← +CVNBot17 left  
4:37:44 PM <@AlexZ_> CVNBot18 restart
4:37:44 PM → +CVNBot14 (voiced) joined  ← +CVNBot18 left  
4:37:49 PM <@AlexZ_> CVNBot19 restart
4:37:49 PM → +CVNBot16 (voiced) joined  ← +CVNBot19 left  
4:37:54 PM <@AlexZ_> CVNBot20 restart
4:37:54 PM → +CVNBot17 (voiced) joined  ← +CVNBot20 left  
4:37:58 PM <@AlexZ_> CVNBot21 restart
4:37:58 PM → +CVNBot18 (voiced) joined  ← +CVNBot21 left  
4:38:02 PM <@AlexZ_> CVNBot22 restart
4:38:03 PM → +CVNBot19 (voiced) joined  ← +CVNBot22 left  
4:38:08 PM <@AlexZ_> CVNBot23 restart
4:38:08 PM → +CVNBot20 (voiced) joined  ← +CVNBot23 left  
4:38:11 PM <@AlexZ_> CVNBot24 restart
4:38:11 PM → +CVNBot21 (voiced) joined  ← +CVNBot24 left  
4:38:16 PM <@AlexZ_> CVNBot25 restart
4:38:16 PM → +CVNBot22 (voiced) joined  ← +CVNBot25 left  
4:38:21 PM <@AlexZ_> CVNBot26 restart
4:38:21 PM → +CVNBot23 (voiced) joined  ← +CVNBot26 left  
4:38:25 PM <@AlexZ_> CVNBot27 restart
4:38:25 PM → +CVNBot24 (voiced) and +CVNBot25 (voiced) joined  ← +CVNBot27 left  
4:38:34 PM <@AlexZ_> SWBot3 restart
4:38:34 PM → +CVNBot26 (voiced) and +CVNBot27 (voiced) joined  ← +SWBot3 left  
4:38:42 PM <@AlexZ_> Cubbie restart
4:38:42 PM → +SWBot3 (voiced) joined  ↔ +Cubbie (voiced) nipped out

**Comment by Krinkle** [comment] 2018-12-30 21:08
Duplicate of #22.

**Closed by Krinkle** 2018-12-30 21:08 UTC
Labels: type-problem
